### ISSUE TITLE
Missing README.md

### ISSUE THREAD

**Issue by vsapiens** [Loptt/fuzzy-controller#1]
There is no readme nor description in this project. @Loptt

**Comment by Loptt** [comment]
Hi @vsapiens. Thanks for your interest in the project. I will be updating the README soon as I gather more information on the project and the requirements stabilize. I'll keep you updated on any changes.

Cheers,
Loptt

**Comment by vsapiens** [comment]
I am still waiting for the readme. I just asked a few hours ago, but it isn't available.

**Comment by Loptt** [comment]
Hi @vsapiens. I invite you to fork this repo and create a README and then you can create a pull request to acknowledge your contribution.

Thanks,
Loptt

**Comment by vsapiens** [comment]
No thank you.
